AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: Todo App - .NET 8 API on AWS Lambda

Parameters:
  DbConnectionString:
    Type: String
    Description: Database connection string


Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: dotnet8
    Architectures:
      - x86_64
    Environment:
      Variables:
        DB_CONNECTION_STRING: !Ref DbConnectionString
    VpcConfig:
      SecurityGroupIds:
        - sg-08ac02274ef8c92d2
      SubnetIds:
        - subnet-05dde8b635b7703fc
        - subnet-055846d5b2798f727
        - subnet-0cfa36703608b443c

Resources:
  TodoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: TodoApi
      Events:
        GetTodos:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: GET
        CreateTodo:
          Type: HttpApi
          Properties:
            Path: /todos
            Method: POST
        ToggleTodo:
          Type: HttpApi
          Properties:
            Path: /todos/{id}/complete
            Method: PATCH
        DeleteTodo:
          Type: HttpApi
          Properties:
            Path: /todos/{id}
            Method: DELETE
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        ProjectReferenceList:
          - ./TodoApi.csproj

Outputs:
  ApiUrl:
    Description: "Your API URL - use this in React app"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"